-- Generated by spliceModule
instance PathInfo ImagePath
    where toPathSegments inp = case inp of
                                   ImagePath arg -> (++) [pack "image-path"] (toPathSegments arg)
          fromPathSegments = ap (segment (pack "image-path") >> return ImagePath) fromPathSegments
instance WithFieldOptic ImageKey
    where withFieldOptic f (Field 1 1) = f (RTraversal (Traversal (_Ctor @"ImageOriginal" . position @1)))
          withFieldOptic f (Field 1 2) = f (RTraversal (Traversal (_Ctor @"ImageOriginal" . position @2)))
          withFieldOptic f (Field 2 1) = f (RTraversal (Traversal (_Ctor @"ImageCropped" . position @1)))
          withFieldOptic f (Field 2 2) = f (RTraversal (Traversal (_Ctor @"ImageCropped" . position @2)))
          withFieldOptic f (Field 3 1) = f (RTraversal (Traversal (_Ctor @"ImageScaled" . position @1)))
          withFieldOptic f (Field 3 2) = f (RTraversal (Traversal (_Ctor @"ImageScaled" . position @2)))
          withFieldOptic f (Field 3 3) = f (RTraversal (Traversal (_Ctor @"ImageScaled" . position @3)))
          withFieldOptic f (Field 4 1) = f (RPrism (Prism (_Ctor @"ImageUpright")))
          withFieldOptic _ _fhop = throwError (PathError ("WithFieldOptic - unexpected field position " ++ (show _fhop ++ (" for " ++ show (typeRep (Proxy @ImageKey))))))
instance ConstructorPosTuple ImageKey
    where withConstructorTuple f (Ctor 1) = f (RPrism (Prism (_Ctor @"ImageOriginal")))
          withConstructorTuple f (Ctor 2) = f (RPrism (Prism (_Ctor @"ImageCropped")))
          withConstructorTuple f (Ctor 3) = f (RPrism (Prism (_Ctor @"ImageScaled")))
          withConstructorTuple f (Ctor 4) = f (RPrism (Prism (_Ctor @"ImageUpright")))
          withConstructorTuple _ _chop = throwError (PathError ("WithConstructorTuple - unexpected constructor position " ++ (show _chop ++ (" for " ++ show (typeRep (Proxy @ImageKey))))))
instance WithFieldOptic ImageShape
    where withFieldOptic f (Field 1 1) = f (RLens (Lens (field @"_imageShapeType")))
          withFieldOptic f (Field 1 2) = f (RLens (Lens (field @"_imageShapeRect")))
          withFieldOptic _ _fhop = throwError (PathError ("WithFieldOptic - unexpected field position " ++ (show _fhop ++ (" for " ++ show (typeRep (Proxy @ImageShape))))))
instance ConstructorPosTuple ImageShape
    where withConstructorTuple f (Ctor 1) = f (RPrism (Prism (_Ctor @"ImageShape")))
          withConstructorTuple _ _chop = throwError (PathError ("WithConstructorTuple - unexpected constructor position " ++ (show _chop ++ (" for " ++ show (typeRep (Proxy @ImageShape))))))
